### ISSUE TITLE
ASUS X455LF Hang sesudah booting selama ±12menit

### ISSUE THREAD

**Issue by hamidkazuo** [JaemanPratama/Hackintosh-EFI-Library-Asus-A455L-X455L-Model#1]
Saya berada di Hackintosh Big Sur, dan saya mengalami masalah saat sudah selesai boot dan setelah dipake selama ±13 menit semua aplikasi yang saya buka tiba-tiba force close, saya coba buka kembali aplikasinya tetep gabisa dibuka, sebelum crash saat ngunjungin sebuah website, safari nya muncul peringatan error secara terus menerus, jalan satu satunya untuk saya saat itu harus restart laptopnya, apakah ada solusi nya ? terimakasih

**Comment by JaemanPratama** [comment]
~~oh ya, saya dulu juga mengalami hal seperti itu, solusi saya menjalankan installer big sur lewat mac os mojave / catalina, kemudian saya install dipartisi kedua~~

**Comment by JaemanPratama** [comment]
![install_big_sur_beta_thumb](https://user-images.githubusercontent.com/89202419/178512112-e6dc19b9-160c-4f0b-aafc-ffb71268bf99.png)

**Comment by hamidkazuo** [comment]
> ![install_big_sur_beta_thumb](https://user-images.githubusercontent.com/89202419/178512112-e6dc19b9-160c-4f0b-aafc-ffb71268bf99.png)

terimakasih, saya sekarang dualboot windows sama mac os bigsur, tapi setelah saya otak-atik di bagian kexts nya sekarang sudah normal kembali, terimakasih untuk efi nya gan 👍

**Comment by JaemanPratama** [comment]
saya melakukan test dengan menambahkan boot-args`-allow_sidecar_ipad` `-force_uni_control` dan tiba tiba finder saya berhenti / crash 

setelah saya menghapus kedua boot-args tersebut, secara ajaibnya finder saya tiba tiba normal kembali

**Comment by JaemanPratama** [comment]
jadi masalahnya mungkin terletak diantara kext / boot-args
