### ISSUE TITLE
Touchpad Not Work

### ISSUE THREAD

**Issue by arfiantorodev** [JaemanPratama/Hackintosh-EFI-Library-Asus-A455L-X455L-Model#4]
Halo ka, mau tanya saya sudah paki EFI ini untuk install macOS Bigsur. Semuanya sudah berjalan normal kecuali touchpad yang masih belum bekerja. apakah ada setting parameter tambahan?
atau ada solusi lain ?
* LAPTOP ASUS A455LF
* 
Terima Kasih

**Comment by JaemanPratama** [comment]
Untuk model touchpad nya apa ya?

Kalau touchpad di EFI ini pakainya Elan ETD0108

Mungkin bisa menggunakan kext ini https://osxlatitude.com/forums/topic/5966-details-about-the-smart-touchpad-driver-features/

kekurangannya :
- kadang bisa mati / nyala sendiri
